### ISSUE TITLE
MapList 显示有问题

### ISSUE THREAD

**Issue by gz65555** [JX3BOX/jx3box-data#3]
- 链接：https://github.com/JX3BOX/jx3box-data/blob/master/data/common/maplist.json
- 我用 GBK 编码打开
![image](https://user-images.githubusercontent.com/6926263/132803631-ec0df0c5-280c-4b0b-a15a-0ed6370bc765.png)

显示有误，希望能得到正确的打开方式

**Comment by iRuxu** [comment]
utf8
